##DataBase Connection
spring.datasource.url=jdbc:mysql://freelance-databases.cjymcuaqqy43.us-east-2.rds.amazonaws.com:3306/cue_ball
spring.datasource.username=root
spring.datasource.password=Time2get$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true
debug=false
##End

## CDN Path for access resources
cdn.base.path=https://data-freelance-project.s3.us-east-2.amazonaws.com/CueBall/resources

base.path.url=https://data-freelance-project.s3.us-east-2.amazonaws.com/CueBall