##DataBase Connection
spring.datasource.url=jdbc:mysql://daw-global-others.cdnzbyuopemp.us-east-2.rds.amazonaws.com:3306/global_donation
spring.datasource.username=root
spring.datasource.password=Aq#357qxp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true
debug=false
##End

## CDN Path for access resources
cdn.base.path=https://resources.dawateislami.net/global/centraldonationadmin/resources

base.path.url=https://resources.dawateislami.net/global/centraldonationadmin