##DataBase Connection
spring.jpa.database=cue_ball
spring.datasource.url=jdbc:postgresql://localhost:5432/cue_ball
spring.database.driverClassName=org.postgresql.Driver
spring.datasource.username=p_user
spring.datasource.password=asadparrot

# JPA Config :-
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update


## CDN Path for access resources
cdn.base.path=http://localhost:8080/CueBallPortal

## JSON path need to work
base.path.url=http://localhost:8080/CueBallPortal

##Asad dev env
